FROM node:25.9-alpine3.22

WORKDIR /app/frontend

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN mkdir -p .next && chown -R node:node /app/frontend
RUN chown -R node:node /app/frontend

USER node
EXPOSE 3000

# CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
