FROM node:25.4-alpine

WORKDIR /app/frontend

COPY package*.json ./
RUN npm install

COPY . .
RUN mkdir -p .next && chown -R node:node /app/frontend
RUN chown -R node:node /app/frontend

USER node
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
