theme: jekyll-theme-minimal

title: Plant-Vita
description: >
  Smart Gardener powered by IoT, AI and Cloud Computing

logo: assets/NameLogo.png

nav:
  - title: Home
    url: /

  - title: Backend
    url: /backend/

  - title: Frontend
    url: /frontend/

  - title: Mobile
    url: /mobile/

  - title: Embedded
    url: /embedded/

  - title: AI Processing
    url: /processing_service/

show_downloads: false

github:
  repository_url: https://github.com/username/Plant-Vita